### ISSUE TITLE
Deployment template has hard coded values, please convert to template

### ISSUE THREAD

**Issue by deepak7093** [samkhune/helm#1]
Helm Template files `deployment.yaml` has hard coded values. Template files shouldn't have any hard-coded values.
```
ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
```
